-- Production Database Population Script
-- Run this in your Replit deployment's SQL runner to populate the database

-- First, let's add a sample of key companies
INSERT INTO companies (id, name, description, website, industry, size, logo, location, created_at) VALUES
(1, 'Tata Consultancy Services', 'Leading global IT services, consulting and business solutions company', 'https://www.tcs.com', 'Information Technology', 'Large (10000+ employees)', null, 'Mumbai', NOW()),
(2, 'Infosys', 'Global leader in next-generation digital services and consulting', 'https://www.infosys.com', 'Information Technology', 'Large (10000+ employees)', null, 'Bangalore', NOW()),
(3, 'Wipro', 'Leading technology services and consulting company', 'https://www.wipro.com', 'Information Technology', 'Large (10000+ employees)', null, 'Bangalore', NOW()),
(4, 'State Bank of India', 'India''s largest public sector bank', 'https://www.sbi.co.in', 'Banking & Financial Services', 'Large (10000+ employees)', null, 'Mumbai', NOW()),
(5, 'HDFC Bank', 'Leading private sector bank in India', 'https://www.hdfcbank.com', 'Banking & Financial Services', 'Large (10000+ employees)', null, 'Mumbai', NOW()),
(6, 'Reliance Industries', 'Leading petrochemicals, oil & gas, and retail conglomerate', 'https://www.ril.com', 'Oil & Energy', 'Large (10000+ employees)', null, 'Mumbai', NOW()),
(7, 'Tata Motors', 'Leading automobile manufacturer in India', 'https://www.tatamotors.com', 'Automotive', 'Large (10000+ employees)', null, 'Mumbai', NOW()),
(8, 'Apollo Hospitals', 'Leading healthcare provider in India', 'https://www.apollohospitals.com', 'Healthcare & Life Sciences', 'Large (10000+ employees)', null, 'Chennai', NOW()),
(9, 'ITC Limited', 'Leading FMCG and consumer goods company', 'https://www.itcportal.com', 'Retail & Consumer Goods', 'Large (10000+ employees)', null, 'Kolkata', NOW()),
(10, 'Asian Paints', 'India''s largest paint company', 'https://www.asianpaints.com', 'Chemical', 'Large (10000+ employees)', null, 'Mumbai', NOW())
ON CONFLICT (id) DO NOTHING;

-- Add sample internships
INSERT INTO internships (id, company_id, title, description, requirements, benefits, location, remote, duration, stipend, skills, start_date, application_deadline, is_active, created_at) VALUES
(1, 1, 'Software Development Intern', 'Work on enterprise software solutions, learn modern development practices, and contribute to real client projects.', 'Computer Science/IT students. Programming knowledge in Java, Python, or JavaScript preferred.', 'Industry exposure, mentorship program, potential full-time offer', 'Mumbai', true, '6 months', '25000', '["Software Development", "Java", "Python", "JavaScript", "Programming", "Enterprise Software"]', '2025-06-01', '2025-05-01', true, NOW()),
(2, 1, 'Data Analytics Intern', 'Work with data analytics teams to analyze business data, create insights, and support decision-making processes.', 'Engineering/Statistics background. Knowledge of SQL, Python, and data visualization tools.', 'Data science training, analytics certification, industry exposure', 'Bangalore', true, '6 months', '28000', '["Data Analytics", "SQL", "Python", "Data Visualization", "Business Intelligence", "Statistics"]', '2025-06-15', '2025-05-15', true, NOW()),
(3, 2, 'Product Management Intern', 'Support product managers in feature development, user research, and product strategy for enterprise software.', 'Engineering/MBA background. Product thinking, user research skills, analytical mindset.', 'Product management mentorship, PM certification, industry networking', 'Bangalore', true, '6 months', '30000', '["Product Management", "User Research", "Product Strategy", "Analytics", "Agile", "Market Research"]', '2025-07-01', '2025-06-01', true, NOW()),
(4, 4, 'Banking Operations Intern', 'Learn banking operations, customer service, and financial products in public sector banking environment.', 'Any graduate, finance/banking interest, customer service orientation.', 'Banking industry exposure, financial services training, PSU experience', 'Mumbai', false, '6 months', '22000', '["Banking Operations", "Customer Service", "Financial Services", "Banking Products", "Operations Management", "Financial Analysis"]', '2025-06-10', '2025-05-10', true, NOW()),
(5, 5, 'Digital Banking Intern', 'Work on digital banking initiatives, fintech solutions, and customer digital experience improvements.', 'Engineering/IT background, fintech interest, digital innovation mindset.', 'Digital banking exposure, fintech training, technology career path', 'Mumbai', true, '6 months', '26000', '["Digital Banking", "Fintech", "Mobile Banking", "Digital Innovation", "Customer Experience", "Technology"]', '2025-06-20', '2025-05-20', true, NOW()),
(6, 6, 'Energy Engineering Intern', 'Work on renewable energy projects, oil & gas operations, and sustainable energy initiatives.', 'Chemical/Petroleum/Electrical Engineering. Energy sector interest, sustainability focus.', 'Energy industry exposure, sustainability training, engineering development', 'Mumbai', false, '6 months', '28000', '["Energy Engineering", "Renewable Energy", "Sustainability", "Oil & Gas", "Engineering", "Clean Technology"]', '2025-07-01', '2025-06-01', true, NOW()),
(7, 7, 'Automotive Engineering Intern', 'Work on vehicle development, automotive technology, and manufacturing processes.', 'Mechanical/Automobile Engineering. Automotive industry interest, engineering design skills.', 'Automotive industry exposure, engineering training, manufacturing experience', 'Pune', false, '6 months', '25000', '["Automotive Engineering", "Vehicle Development", "Manufacturing", "Engineering Design", "Automotive Technology", "Quality Control"]', '2025-06-25', '2025-05-25', true, NOW()),
(8, 8, 'Healthcare Management Intern', 'Support healthcare operations, patient services, and hospital administration.', 'Healthcare/Hospital Management background. Healthcare industry interest, service orientation.', 'Healthcare industry exposure, hospital operations training, medical administration', 'Chennai', false, '6 months', '23000', '["Healthcare Management", "Hospital Administration", "Patient Services", "Healthcare Operations", "Medical Administration", "Healthcare"]', '2025-07-15', '2025-06-15', true, NOW()),
(9, 9, 'Marketing Intern', 'Work on FMCG marketing campaigns, brand management, and consumer research for consumer goods.', 'Marketing/MBA background. Brand management interest, consumer research skills, creative thinking.', 'FMCG marketing exposure, brand management training, consumer insights', 'Kolkata', false, '6 months', '24000', '["Marketing", "Brand Management", "Consumer Research", "FMCG Marketing", "Market Research", "Brand Strategy"]', '2025-08-01', '2025-07-01', true, NOW()),
(10, 10, 'Chemical Engineering Intern', 'Work on paint formulation, chemical processes, and quality control for paint manufacturing.', 'Chemical Engineering. Paint/Chemical industry interest, laboratory skills, quality focus.', 'Chemical industry exposure, paint technology training, R&D experience', 'Mumbai', false, '6 months', '26000', '["Chemical Engineering", "Paint Technology", "Chemical Processes", "Quality Control", "Laboratory Skills", "Manufacturing"]', '2025-06-01', '2025-05-01', true, NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset sequences to continue from where we left off
SELECT setval('companies_id_seq', (SELECT MAX(id) FROM companies));
SELECT setval('internships_id_seq', (SELECT MAX(id) FROM internships));